import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Nav from "@/components/navigation/nav";
import "./globals.css";

const roboto = Roboto({
  weight: ["400", "500", "700", "900"],
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={roboto.className}
      >
        <div className="flex-grow px-6 md:px-12 mx-auto max-w-8xl">
          <Nav />
          {children}
        </div>
      </body>
    </html>
  );
}
